baseURL: "https://ueda270.github.io/"
title: "27ログ"
theme: "PaperMod"
languageCode: "ja-jp"
defaultContentLanguage: "ja"

# New pagination format
pagination:
  pagerSize: 5

menu:
  main:
    - identifier: posts
      name: 記事一覧
      url: /posts/
      weight: 10
    - identifier: tags
      name: タグ
      url: /tags/
      weight: 20
    - identifier: about
      name: このブログについて
      url: /about/
      weight: 30

params:
  env: production # To ensure OpenGraph tags are always included
  defaultTheme: auto
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true

  homeInfoParams:
    Title: "27ログ"
    Content: "日記とか備忘録とか。"
